---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      provider: fabric8
      app: deployment-strategy-type-919
      version: 3.5-SNAPSHOT
      group: io.fabric8.devops.apps
    name: fabric8-docker-registry
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        provider: fabric8
        app: deployment-strategy-type-919
        group: io.fabric8
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          provider: fabric8
          app: deployment-strategy-type-919
          version: 3.5-SNAPSHOT
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: registry:2
          imagePullPolicy: IfNotPresent
          name: fabric8-docker-registry
          ports:
          - containerPort: 5000
            name: http
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
          - mountPath: /var/lib/registry
            name: fabric8-docker-registry-storage
            readOnly: false
        initContainers:
        - command:
          - chmod
          - "777"
          - /var/lib/registry
          image: busybox
          imagePullPolicy: IfNotPresent
          name: fmp-volume-permission
          volumeMounts:
          - mountPath: /var/lib/registry
            name: fabric8-docker-registry-storage
        volumes:
        - name: fabric8-docker-registry-storage
          persistentVolumeClaim:
            claimName: fabric8-docker-registry-storage
